project:
  type: website
  output-dir: docs

execute: 
  freeze: auto

website:
  title: "@GNOBLET"
  description: "My quarto website"
  image: img/my_image.jpg
  site-url: "https://gnoblet.github.io/"
  navbar:
    pinned: true
    
    # your sub-pages
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Projects"
        menu:
          - projects/TidyTuesdays.qmd
    
    # your social media handles
    right:
    - icon: github
      href: https://github.com/gnoblet
    - text: "{{< fa brands bluesky >}}"      
      href: https://bsky.app/profile/gnoblet.bsky.social
    - icon: linkedin
      href: https://www.linkedin.com/in/gnoblet/
    - icon: envelope
      aria-label: email
      href: "mailto:gnoblet@zaclys.net"

  # Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2024 Guillaume Noblet CC BY-SA 4.0</span>
    right: |
      <span class="faux-block"><a href="https://github.com/gnoblet/gnoblet.github.io">View source on GitHub</a></span>

format:
  html:
    fontsize: 1.1em
    theme: 
      - jolla
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true



head:
  - <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">